import { MediaItem } from "./types"

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: "audio-1",
    title: "Penthouse Freestyle (VIP Master)",
    type: "song",
    duration: "3:42",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Dark R&B / Trap",
    bpm: "97 BPM",
    tags: ["dark ambient", "trap beat"],
    price: 29.0,
    thumbnailUrl: "/avatar.jpg",
  },
  {
    id: "audio-2",
    title: "Shadows in Amanda (Stems & Audio)",
    type: "song",
    duration: "2:58",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Electronic",
    bpm: "117 BPM",
    tags: ["synthesizer", "club mix"],
    price: 29.0,
    thumbnailUrl: "/avatar.jpg",
  },
  {
    id: "video-1",
    title: "Tokyo Drift Sessions (4K Studio Visualizer)",
    type: "video",
    duration: "4:05",
    releaseDate: "2026",
    isExclusive: true,
    genre: "4K Film",
    tags: ["4k visualizer", "studio session"],
    price: 29.0,
    thumbnailUrl: "/avatar.jpg",
  },
  {
    id: "video-2",
    title: "Studio Live Jam & Production Breakdown",
    type: "video",
    duration: "18:22",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Behind The Scenes",
    tags: ["exclusive film", "breakdown"],
    price: 29.0,
    thumbnailUrl: "/avatar.jpg",
  },
]

