import { MediaItem } from "./types"

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: "song-1",
    title: "Midnight Echoes (VIP Mix)",
    type: "song",
    duration: "3:42",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Dark Ambient / Synth",
  },
  {
    id: "song-2",
    title: "Shadows in Amanda",
    type: "song",
    duration: "2:58",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Electronic",
  },
  {
    id: "song-3",
    title: "After Dark Transmission",
    type: "song",
    duration: "4:15",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Alternative",
  },
  {
    id: "song-4",
    title: "Lost Frequency (Acoustic)",
    type: "song",
    duration: "3:10",
    releaseDate: "2026",
    isExclusive: false,
    genre: "Acoustic",
  },
  {
    id: "video-1",
    title: "Midnight Echoes - Official Music Video (4K)",
    type: "video",
    duration: "4:05",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Official Video",
  },
  {
    id: "video-2",
    title: "Studio Session & Unreleased Stems Breakdown",
    type: "video",
    duration: "18:22",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Behind The Scenes",
  },
  {
    id: "video-3",
    title: "Live in Tokyo - Full Performance Replay",
    type: "video",
    duration: "35:40",
    releaseDate: "2026",
    isExclusive: true,
    genre: "Concert Film",
  },
]
